version: "2.1"

services:
  engage:
    image: dadarek/wait-for-dependencies
    depends_on:
      - database
      - php
      - nginx
    command: database:3306 php:9000 nginx:80
  nginx:
    image: prooph/nginx:www
    ports:
      - "80:80"
      - "443:443"
    links:
      - php:php

    depends_on:
      - database
      - php
      - dataphp
    volumes:
      - ./machine/nginx/sites-enabled:/etc/nginx/sites-enabled
    volumes_from:
      - dataphp

  php:
    env_file: "${PHP_ENV_FILE}"
    image: "alterway/php:${PHP_VERSION}-fpm"
    depends_on:
     - database
    links:
     - database:database
    volumes_from:
     - dataphp

  dataphp:
    image: alpine:latest
    volumes:
      - "${SITES_FOLDER}:/var/www"
    command: /bin/true

  database:
    image: "mysql:${MYSQL_VERSION}"
    env_file: "${MYSQL_ENV_FILE}"
    ports:
      - "3306:3306"
    volumes:
      - ./machine/mysql/databases:/var/lib/mysql
      - ./machine/mysql/cnf:/etc/mysql/conf.d